# Generated by Django 4.1.7 on 2023-08-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedevicelog',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_in_logs', to='company.employee'),
        ),
        migrations.AddField(
            model_name='employeedevicelog',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checked_out_logs', to='company.employee'),
        ),
        migrations.AddField(
            model_name='employeedevicelog',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedevicelog',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedevicelog',
            name='condition_when_checked_in',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedevicelog',
            name='condition_when_checked_out',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
