# Generated by Django 4.1.7 on 2023-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employeedevicelog_checked_in_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedevice',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
